title: Your Name
email: you@example.com
description: "A blog and portfolio"
theme: jekyll-theme-cayman
markdown: kramdown

plugins:
  - jekyll-feed

collections:
  posts:
    output: true
  portfolio:
    output: true

